[versions]
qqbot="1.3.2-dev"
logback="1.5.6"
okio="3.9.0"
shadow="8.1.1"
lombok="1.18.34"
gson="2.11.0"
# implementation 'com.google.code.gson:gson:2.11.0'
[libraries]
qqbot-sdk={ module="me.zhenxin:qqbot-sdk", version.ref="qqbot" }
logback-classic={ module="ch.qos.logback:logback-classic", version.ref="logback" }
logback-core={ module="ch.qos.logback:logback-core", version.ref="logback" }
okio={ module="com.squareup.okio:okio", version.ref="okio" }
lombok={ module = "org.projectlombok:lombok", version.ref="lombok"}
gson={ module = "com.google.code.gson:gson", version.ref="gson"}

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }